apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000 # port interne du cluster
      targetPort: 5000 # port du conteneur
      nodePort: 30080 # port exposé sur Minikube
  type: NodePort
